server:
  port: ${port:9411}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: rootroot
    initialization-mode: always
    continue-on-error: true
    dbcp2:
      #初始化连接:连接池启动时创建的初始化连接数量
      initial-size: 50
      #从连接池获取一个连接时，最大的等待时间,连接池会等待N毫秒，等待不到，则抛出异常
      max-wait-millis: 60000
      #最大空闲连接:连接池中容许保持空闲状态的最大连接数量,超过的空闲连接将被释放,如果设置为负数表示不限制
      max-idle: 100
      #通过这个池创建连接的默认自动提交状态。如果不设置，则setAutoCommit 方法将不被调用
      default-auto-commit: true
      #通过这个池创建连接的默认只读状态
      default-read-only: false
      #指明在从池中租借对象时是否要进行验证有效，如果对象验证失败，则对象将从池子释放，然后我们将尝试租借另一个
      test-on-borrow: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: zipkin-server
zipkin:
  storage:
    type: mysql
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8050/eureka/
grpc:
  server:
    address: 0.0.0.0
    port: 9093