grpc:
  client:
    GLOBAL:
      enableKeepAlive: true
    integration-business-service:
      address: static://localhost:9094
      negotiationType: PLAINTEXT  #测试模式开启明文，上线需要增加证书认证
  server:
    address: 0.0.0.0
    port: 9092
logging:
  confing: classpath:log4j2.xml
multipart:
  enabled: true
  max-file-size: 100
  max-request-size: 100
server:
  port: ${port:8010}
spring:
  application:
    name: integration-account-service
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true
  datasource:
    user:
      initialSize: 10
      maxActive: 2000
      minEvictableIdleTimeMillis: 300000
      minIdle: 10
      name: integration_db
      password: rootroot
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 3000
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/integration?useUnicode=true&characterEncoding=UTF-8&useCursorFetch=true&noAccessToProcedureBodies=true
      username: root
  http:
    encoding:
      charset: UTF-8

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8050/eureka/
