server:
  port: ${port:9411}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zipkin-server
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8050/eureka/
grpc:
  server:
    address: 0.0.0.0
    port: 9093