/*
 * This file is generated by jOOQ.
*/
package com.shigen.wang.jooq;


import com.shigen.wang.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in integration
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>integration.user</code>.
     */
    public static final User USER = com.shigen.wang.jooq.tables.User.USER;
}
