grpc:
  client:
    GLOBAL:
      enableKeepAlive: true
    integration-account-service:
      address: static://localhost:9092
      negotiationType: PLAINTEXT
  server:
    address: 0.0.0.0
    port: 9094
logging:
  confing: classpath:log4j2.xml
server:
  port: ${port:8020}
spring:
  application:
    name: integration-business-service
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
      sampler:
        probability: 1
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8050/eureka/
