/*
 * This file is generated by jOOQ.
*/
package com.shigen.wang.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -68963669;

    private Integer id;
    private String  name;
    private Integer gender;
    private String  email;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.gender = value.gender;
        this.email = value.email;
    }

    public User(
        Integer id,
        String  name,
        Integer gender,
        String  email
    ) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.email = email;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(gender);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
